- hosts: localhost
  become: yes
  roles:
    - role: logstash-role
      logstash_defaults: |
        LS_HEAP_SIZE="256m"
        LS_OPTS="-r --config.reload.interval 2"

      logstash_inputs: |
        file {
              path => "/var/log/auth.log"
             }

      logstash_filters: |
        # dummy

      logstash_outputs: |
        # dummy

      logstash_plugins:
        - { plugin_name: "logstash-filter-de_dot" }