---

- name: Install Logstash Plugins
  environment:
    JAVA_OPTS: "{{ logstash_java_opts }}"
  command: '{{ logstash_home }}/bin/{{ logstash_plugin_bin }} install {{ item.plugin_name }}'
  with_items: "{{ logstash_plugins }}"
