---

- name: Generate startup.options file
  template:
    src: etc/logstash/startup.options.j2
    dest: "{{ logstash_settings_dir }}startup.options"
    owner: root
    group: root
    mode: 0644
  notify:
   - setup logstash service
   - reenable logstash.service
   - restart logstash
