---

# tasks file for logstash-role

- include: 010_logstash_requirements.yml
  tags: [logstash, logstash-requirements]

- include: 020_logstash_installation_Debian.yml
  when: ansible_os_family == "Debian"
  tags: [logstash, logstash-install, logstash-install-debian]

- include: 025_logstash_installation_RedHat.yml
  when: ansible_os_family == "RedHat"
  tags: [logstash, logstash-install, logstash-install-redhat]

- include: 030_logstash_system_install.yml
  when: logstash_new_way_configure
  tags: [logstash, logstash-install, logstash-system-install]

- include: 040_logstash_plugins.yml
  when: install_logstash.changed
  tags: [logstash, logstash-install, logstash-plugins]

- include: 050_logstash_pipeline_configuration.yml
  tags: [logstash, logstash-config, logstash-configuration]

- meta: flush_handlers